// Package licenses provides embedded third-party license data collected at
// build time. The JSON file is generated by cmd/collect-licenses.
package licenses

import (
	_ "embed"
	"encoding/json"
	"sync"
)

//go:embed licenses.json
var rawJSON []byte

// LicenseData holds all license information embedded in the binary.
type LicenseData struct {
	Generated    string              `json:"generated"`
	Project      ProjectLicense      `json:"project"`
	Dependencies []DependencyLicense `json:"dependencies"`
}

// ProjectLicense holds the project's own license.
type ProjectLicense struct {
	Name        string `json:"name"`
	Version     string `json:"version"`
	LicenseType string `json:"license_type"`
	LicenseText string `json:"license_text"`
}

// DependencyLicense holds a single dependency's license info.
type DependencyLicense struct {
	Module      string `json:"module"`
	Version     string `json:"version"`
	LicenseType string `json:"license_type"`
	LicenseText string `json:"license_text"`
	Direct      bool   `json:"direct"`
}

var (
	once     sync.Once
	cached   *LicenseData
	cacheErr error
)

// Load returns the embedded license data. The result is cached after the first call.
func Load() (*LicenseData, error) {
	once.Do(func() {
		var data LicenseData
		cacheErr = json.Unmarshal(rawJSON, &data)
		if cacheErr == nil {
			cached = &data
		}
	})
	return cached, cacheErr
}
